language: cpp

sudo: false
cache: ccache

notifications:
  irc: "chat.freenode.net##crow"

compiler:
  - gcc

env:
  matrix:
          #- COMPILER=g++-4.8 CCOMPILER=gcc-4.8 PUSH_COVERAGE=ON
          #- COMPILER=g++-4.9 CCOMPILER=gcc-4.9
          #    - COMPILER=g++-5 CCOMPILER=gcc-5
          #- COMPILER=clang++-3.6 CCOMPILER=clang-3.6
    - COMPILER=x86_64-w64-mingw32-g++ CCOMPILER=x86_64-w64-mingw32-gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - g++-4.9
      - g++-5
      - clang-3.6
      - libboost1.55-all-dev
      - python-pip
      - mingw-w64

install:
  - if [ "$PUSH_COVERAGE" == "ON" ]; then pip install --user git+git://github.com/eddyxu/cpp-coveralls.git; fi

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_SYSTEM_NAME=Windows

script: make -j2 && ctest -j2

after_success:
  - cd ..
  - if [ "$PUSH_COVERAGE" == "ON" ]; then coveralls --gcov gcov-4.8 -i include --gcov-options '\-lp'; fi
